services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "3306:3306"
    command: ["--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci"]
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 3s
      retries: 20

  rabbitmq:
    image: rabbitmq:3.13-management
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: secret
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # 관리 UI http://localhost:15672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  redis:
    image: redis:7-alpine
    command: [ "redis-server", "--appendonly", "yes", "--requirepass", "redispw" ]
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "redispw", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - redis-data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydatabase?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: myuser
      SPRING_RABBITMQ_PASSWORD: secret

      SPRING_PROFILES_ACTIVE: prod

      APP_BASE_M3U8_DIR: /file/m3u8
      APP_BASE_TS_DIR: /file/ts
    volumes:
      - ./files/m3u8:/file/m3u8   # m3u8 스냅샷 저장소
      - ./files/ts:/file/ts       # ts 스냅샷 저장소
    ports:
      - "8080:8080"   # 앱 외부 노출

volumes:
  rabbitmq-data:
  redis-data:
  m3u8-volume:
  ts-volume:
